# Generated by Django 4.2.11 on 2025-04-10 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentRequest',
            fields=[
                ('req_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('req_status', models.IntegerField(choices=[(1, 'Created'), (2, 'Pending'), (3, 'Returned'), (4, 'Failed')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='captures/')),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
