# Generated by Django 4.2.11 on 2025-04-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identrequest',
            name='status_reason',
            field=models.TextField(null=True),
        ),
    ]
