# Generated by Django 4.2.20 on 2025-04-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify_api', '0003_identrequest_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='identrequest',
            name='gps_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identrequest',
            name='gps_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
