# Generated by Django 4.2.20 on 2025-04-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify_api', '0004_identrequest_gps_latitude_identrequest_gps_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='identrequest',
            name='gps_lat_north',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identrequest',
            name='gps_lon_west',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
