# Generated by Django 4.2.11 on 2025-03-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profile_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
