# Generated by Django 4.2.11 on 2025-03-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, default='profile/defaultprofile.png', upload_to='profile/'),
        ),
    ]
