# Generated by Django 4.2.11 on 2025-03-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_capturedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedimage',
            name='image',
            field=models.ImageField(upload_to='captures/'),
        ),
    ]
