# Generated by Django 4.2.11 on 2025-04-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_capturedimage_image'),
        ('home', '0012_remove_profile_aboutme_profile_about_me_and_more'),
    ]

    operations = [
    ]
