# Generated by Django 4.2.11 on 2025-04-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20250407_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(default='badges/default_image.png', upload_to='badges/'),
        ),
    ]
