# Generated by Django 4.2.11 on 2025-04-10 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identify_api', '0001_initial'),
        ('home', '0014_badge_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturedimage',
            name='image',
        ),
        migrations.AddField(
            model_name='capturedimage',
            name='ident_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identify_api.identrequest'),
        ),
    ]
