# Generated by Django 4.2.20 on 2025-04-22 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_leaderboardmanager_leaderboardentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_captures', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='profile',
        ),
        migrations.DeleteModel(
            name='LeaderboardManager',
        ),
        migrations.DeleteModel(
            name='LeaderboardEntry',
        ),
    ]
