# Generated by Django 4.2.20 on 2025-04-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_leaderboardentry_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_id', models.IntegerField()),
                ('most_captures', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='rank',
            field=models.IntegerField(default=8),
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
