# Generated by Django 4.2.20 on 2025-04-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_leaderboardmanager_alter_leaderboardentry_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='rank',
            field=models.IntegerField(default=9),
        ),
    ]
