# Generated by Django 4.2.20 on 2025-04-21 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_profile_test_alter_leaderboardentry_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
    ]
