# Generated by Django 4.2.20 on 2025-05-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_clientpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=120)),
                ('facts', models.TextField()),
            ],
        ),
    ]
