# Generated by Django 4.2.20 on 2025-04-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_profile_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardmanager',
            name='starting_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='rank',
            field=models.IntegerField(default=999999),
        ),
    ]
