# Generated by Django 4.2.20 on 2025-05-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_gptfacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptfacts',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gptfacts',
            name='facts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
