from .home import home_view
from .profile import profile_view
from .capture import capture_view
from .plantdex import plantdex_view
from .badges import badges_view
from .map import map_view
from .social import social_view
from .settings import settings_view
from .about import about_view
from .logout import logout_view
