name: Build Docker and Deploy
on:
  push:
    branches: ['main', 'deployment-fixes']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into gchr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: uccs-sp25-cs4300-cs5300-1
          password: ${{ secrets.PACKAGES_PAT }}

      - name: Build
        run: |
          docker build -t ghcr.io/uccs-sp25-cs4300-cs5300-1/leafquest:latest .

      - name: Push Package
        run: |
          docker push ghcr.io/uccs-sp25-cs4300-cs5300-1/leafquest:latest
