name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai_code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensures we get the previous commit for diff

      - name: Install Python and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai PyGithub
          pip install -r requirements.txt

      - name: Generate Pylint report
        run: |
          python -m pylint --recursive=y LeafQuest/ > pylint.txt

      - name: Get PR Diff
        run: |
          git fetch
          git diff origin/${{ github.event.pull_request.base.ref }} > diff.txt

      - name: Run AI Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python ai-code-review.py

      - name: Upload Review Artifact
        uses: actions/upload-artifact@v4
        with:
          name: review-artifacts
          path: |
            feedback.md
            pylint.txt

      - name: Fix OpenAI silliness
        run: |
          sed -i 's/```markdown//' feedback.md
          sed -i '${s/```$//}' feedback.md

      - name: Comment Feedback on Pull Request
        uses: thollander/actions-comment-pull-request@v3.0.1
        with:
          file-path: feedback.md

      - name: Comment Linting Report on Pull Request
        uses: thollander/actions-comment-pull-request@v3.0.1
        with:
          file-path: pylint.txt

      - name: Cleanup
        run: rm diff.txt feedback.md
