name: Lint Project

on:
  # Run on pushes and pull requests
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.12 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Pylint Report
        id: pylint
        run: |
          python -m pylint --recursive=y --output=pylint-report.txt LeafQuest/
          sed -i '1i ```' pylint-report.txt
          sed -i '$a ```' pylint-report.txt

      - name: Upload linter results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pylint-results
          path: pylint-report.txt

      - name: Comment linter results on PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3.0.1
        with:
          file-path: pylint-report.txt
